name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4
        timeout-minutes: 1
        continue-on-error: true
        if: matrix.os != 'macos-latest' # Cache seems to messing up macOS build
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: 'true'
          default: 'true'

      - name: Build
        run: cargo build --locked

      - name: Test
        run: cargo test

  clippy:
    name: Clippy

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          components: clippy
          override: 'true'
          default: 'true'

      - name: Use clippy to lint code
        run: cargo clippy -- -D warnings

  fmt:
    name: Fmt

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          components: rustfmt
          override: 'true'
          default: 'true'

      - name: Check code formatting
        run: ./fmt.sh
